/**
 * ChallengesScreen — Full list of AI-generated Eco-Challenges.
 *
 * Groups challenges: active first, completed at the bottom.
 * Shows an "AI Powered" badge when challenges were generated by GPT.
 */

import React, { useCallback, useState } from 'react';
import {
  View, Text, ScrollView, StyleSheet,
  RefreshControl, ActivityIndicator, Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';

import ChallengeCard from '../components/ChallengeCard';
import { useUser } from '../context/UserContext';
import { getUserChallenges, completeChallenge, Challenge, getHistory } from '../services/api';

export default function ChallengesScreen() {
  const { userId, updateCoins } = useUser();
  const [challenges, setChallenges] = useState<Challenge[]>([]);
  const [hotSpot, setHotSpot] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const loadChallenges = async () => {
    if (!userId) return;
    try {
      const [chData, historyData] = await Promise.all([
        getUserChallenges(userId),
        getHistory(userId),
      ]);
      setChallenges(chData);
      if (historyData.length > 0) {
        setHotSpot(historyData[0].hot_spot);
      }
    } catch (err) {
      console.warn('Failed to load challenges:', err);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  // Reload whenever this tab is focused
  useFocusEffect(useCallback(() => { loadChallenges(); }, []));

  const handleComplete = async (id: string) => {
    if (!userId) return;
    const result = await completeChallenge(id, userId);
    updateCoins(result.new_balance, result.new_level);
    setChallenges((prev) =>
      prev.map((c) => c.id === id ? { ...c, completed: true } : c),
    );
  };

  const active = challenges.filter((c) => !c.completed);
  const completed = challenges.filter((c) => c.completed);

  if (loading) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color="#00E676" />
      </View>
    );
  }

  // Determine hot spot label & icon
  const isTransport = hotSpot?.includes('km by');
  const hotSpotCategory = isTransport ? 'Transport' : 'Diet';
  const hotSpotIcon = isTransport ? '🚗' : '🥩';

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView
        style={styles.scroll}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); loadChallenges(); }} tintColor="#00E676" />}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.headerColumn}>
          <Text style={styles.title}>AI Powered Challenges</Text>
          <Text style={styles.titleHighlight}>for Today</Text>
        </View>

        {/* Hot Spot Banner (Matches Mockup) */}
        {hotSpot && hotSpot !== "No significant activities logged" && (
          <View style={styles.hotSpotCard}>
            <View style={styles.hotSpotHeaderRow}>
              <Text style={styles.hotSpotHeader}>HOT SPOT</Text>
              <View style={styles.warningCircle}>
                <Ionicons name="flame" size={14} color="#FF5252" />
              </View>
            </View>
            <Text style={styles.hotSpotText}>
              Your {hotSpotCategory} Footprint is High! {hotSpotIcon}
            </Text>
            <Text style={styles.hotSpotSub}>{hotSpot}</Text>
          </View>
        )}

        {active.length === 0 && completed.length === 0 ? (
          <View style={styles.emptyBox}>
            <Text style={styles.emptyEmoji}>📋</Text>
            <Text style={styles.emptyTitle}>No challenges yet</Text>
            <Text style={styles.emptySub}>Log your daily activities to get personalised AI challenges!</Text>
          </View>
        ) : (
          <>
            {active.length > 0 && (
              <View style={styles.section}>
                {active.map((ch, idx) => (
                  <ChallengeCard key={ch.id} challenge={ch} index={idx} onComplete={handleComplete} />
                ))}
              </View>
            )}

            {completed.length > 0 && (
              <View style={styles.section}>
                <Text style={styles.sectionLabel}>Completed ✅</Text>
                {completed.map((ch, idx) => (
                  <ChallengeCard key={ch.id} challenge={ch} index={idx + active.length} onComplete={handleComplete} />
                ))}
              </View>
            )}
          </>
        )}

        <View style={{ height: 100 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#FAF8F5' },
  scroll: { flex: 1, paddingHorizontal: 20 },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#FAF8F5' },
  headerColumn: { marginTop: 20, marginBottom: 20 },
  title: {
    color: '#1A1A1A',
    fontSize: 24,
    fontWeight: '800',
    fontFamily: Platform.select({
      ios: 'Georgia',
      android: 'serif',
      web: 'Georgia, serif',
    }),
  },
  titleHighlight: {
    color: '#2C5E43',
    fontSize: 24,
    fontWeight: '800',
    marginTop: 2,
    fontFamily: Platform.select({
      ios: 'Georgia',
      android: 'serif',
      web: 'Georgia, serif',
    }),
  },
  hotSpotCard: {
    backgroundColor: '#FAF0ED', borderRadius: 16, padding: 20,
    borderWidth: 1, borderColor: '#F5C2B8', marginBottom: 24,
  },
  hotSpotHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  hotSpotHeader: { color: '#B54D3D', fontSize: 11, fontWeight: '800', letterSpacing: 1 },
  warningCircle: {
    width: 22, height: 22, borderRadius: 11, backgroundColor: '#FFFFFF',
    borderWidth: 1, borderColor: '#F5C2B8', alignItems: 'center', justifyContent: 'center',
  },
  hotSpotText: { color: '#1A1A1A', fontSize: 16, fontWeight: '700', marginBottom: 2 },
  hotSpotSub: { color: '#8A857A', fontSize: 13, fontWeight: '600' },
  emptyBox: {
    alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 16,
    padding: 40, marginTop: 40, borderWidth: 1, borderColor: '#E6E2D8',
  },
  emptyEmoji: { fontSize: 48, marginBottom: 12 },
  emptyTitle: {
    color: '#1A1A1A',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
    fontFamily: Platform.select({
      ios: 'Georgia',
      android: 'serif',
      web: 'Georgia, serif',
    }),
  },
  emptySub: { color: '#8A857A', fontSize: 14, textAlign: 'center', lineHeight: 20 },
  section: { marginBottom: 8 },
  sectionLabel: { color: '#8A857A', fontSize: 13, fontWeight: '700', marginBottom: 10, textTransform: 'uppercase', letterSpacing: 0.5 },
});
